apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: sih
data:
  MILVUS_LITE_DB: "/data/milvus.db"
  FLASK_ENV: "development"
  NEXT_PUBLIC_BASE_URL: "http://backend:5000"
  NEXT_TELEMETRY_DISABLED: "1"
